[package]
name = "chip_8_emulator"
version = "0.1.0"
authors = ["Nick Wang nickwang508@gmail.com"]
edition = "2018"

[dependencies]
rand = "0.6.5"
piston = "0.49.0"
piston2d-graphics = "0.36.0"
pistoncore-glutin_window = "0.63.0"
piston2d-opengl_graphics = "0.72.0"
